<?php

namespace LoginBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findTop()
    {
        $query = $this->getEntityManager()
            ->createQuery(" SELECT c FROM LoginBundle:User c
     ORDER BY c.score DESC  ");
        $query=$query->setMaxResults(7);
        return $query->getResult();
    }
    public function inviter($id_event)
    {
        $rawSql = "SELECT * FROM user JOIN participation ON participation.user_id = user.id and participation.event_id=".$id_event;
        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);
        return $stmt->fetchAll();
    }
    public function membre($id_event)
    {
        $rawSql = "SELECT * FROM user JOIN participation ON participation.user_id = user.id and participation.event_id=".$id_event;
        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);
        return $stmt->fetchAll();
    }
}
