<?php

namespace MontageBundle\Repository;

/**
 * PieceDeRechangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceDeRechangeRepository extends \Doctrine\ORM\EntityRepository
{
}
