<?php

namespace MontageBundle\Repository;

/**
 * VeloPersoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeloPersoRepository extends \Doctrine\ORM\EntityRepository
{
}
