<?php

namespace DemandeBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{

    public function findMessage(){
        $query = $this->createQueryBuilder('M');
        $query->addOrderBy('M.dateEnvoi', 'ASC');
        return $query->getQuery()->getResult();
    }
}
