<?php

namespace DemandeBundle\Repository;

/**
 * OrdreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdreRepository extends \Doctrine\ORM\EntityRepository
{
}
