<?php

namespace ECommerceBundle\Repository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    public function Cart_user_id($User_Id)
    {
        $query = $this->createQueryBuilder('c');
        $query->Where("c.user=:uid")->setParameter('uid',$User_Id);
        return $query->GetQuery()->getResult();

        /*$em = $query = $this->getEntityManager();
        $RAW_SQL = "SELECT * from Cart  where user_id=:uid ";
        $statement = $em->getConnection()->prepare($RAW_SQL);
        $statement->bindValue('uid',$User_Id);
        $statement->execute();
        $result = $statement->fetchAll();
        //  var_dump($result);
        return  $result;*/
    }

    public function Cart_user_id_product_id($User_Id,$id_product)
    {
        $query = $this->createQueryBuilder('c');
        $query->Where("c.user=:uid")->setParameter('uid',$User_Id)
            ->andWhere("c.product=:pid")->setParameter('pid',$id_product);
        return $query->GetQuery()->getOneOrNullResult();
    }

   /* public function Cart_user_id_product_id2($User_Id,$id_product)
    {
        $query = $this->createQueryBuilder('c');
        $query->Where("c.user=:uid")->setParameter('uid',$User_Id)
            ->andWhere("c.product=:pid")->setParameter('pid',$id_product);
        return $query->GetQuery()->getOneOrNullResult();
    }*/

    public function findUser_id($User_Id)
    {
        $query = $this->createQueryBuilder('c');
        $query->Where("c.user=:uid")->setParameter('uid',$User_Id);
        return $query->GetQuery()->getResult();
    }


}
