<?php

namespace ECommerceBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindAllByProductRefrence($refrence)
    {
      /*  $query = $this->getEntityManager()
            //->createQuery("select id from ECommerceBundle:Product p inner join ECommerceBundle:Image i ON i.product=p.id where  p.refrence=:ref ")
            ->createQuery("SELECT i.image from ECommerceBundle:Product p inner join ECommerceBundle:Image i ON i.product=p.id where p.refrence=:ref ")
            ->setParameter('ref',$refrence);

        return $query->getResult();*/
      //  echo 'eza';
      $em = $query = $this->getEntityManager();
      $RAW_SQL = "SELECT i.id,image,ordrer,product from Image i inner join Product p ON i.product=p.id where p.refrence=:ref ";
      $statement = $em->getConnection()->prepare($RAW_SQL);
      $statement->bindValue('ref',$refrence);
      $statement->execute();
      $result = $statement->fetchAll();
      //  var_dump($result);
      return  $result;

    }

    public function findByProducts($id)
    {
        $query = $this->createQueryBuilder('p');
        $query->Where("p.product=:pid")->setParameter('pid',$id);
        return $query->GetQuery()->getResult();
    }
}
