<?php

namespace EventBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public  function particpant()
{
    $rawSql = "SELECT * FROM evenement inner join participation on  evenement.id=participation.event_id order by  participation.event_id";

    $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
    $stmt->execute([]);
    return $stmt->fetchAll();
}
public function findByUser($id)
{
     $rawSql = "SELECT * FROM participation inner join evenement on  participation.event_id=evenement.id where user_id=".$id;
    $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
    $stmt->execute([]);
    return $stmt->fetchAll();
}
public function annuler($event_id,$user_id)
{
    $rawSql = "DELETE FROM participation WHERE event_id=".$event_id." and user_id=".$user_id;
    $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
    $stmt->execute([]);
}

    public function nombreParticpant($event_id)
    {
        $rawSql = "SELECT COUNT(*) FROM participation  where event_id=".$event_id;
        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);
    }

}
