<?php

namespace EventBundle\Repository;

/**
 * TrophetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrophetRepository extends \Doctrine\ORM\EntityRepository
{
}
