<?php

namespace ForumBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function count($id_sujet)
    {
        $rawSql = "SELECT count(*) FROM commentaire WHERE sujet_id=".$id_sujet." group by sujet_id ";
        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);
        return $stmt->fetchAll();
    }
    public function commantaires(){
        $query=$this->getEntityManager()->createQuery("SELECT f FROM ForumBundle:commentaire f order by f.id desc ");
        return $query->getResult();
    }
}
